version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  
    command: nodemon server.js
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"               
    volumes:
      - ./frontend:/usr/src/app   
      - /usr/src/app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true  
    command: npm run dev
    restart: always
